# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
      rev = "9fcf5d41922f40a56f7da2174d0446580d249490";
      hash = "sha256-gxuI13PkNTRFhq8aQqmRBCicfS4mAOuEzb9dEdfRJVk=";
    };
    patches = patches ++ [];
  }) // {
  version = "9fcf5d41922f40a56f7da2174d0446580d249490";
  yarnHash = "sha256-P7KswzsCusyiS4MxUFnC1HYMTQ6fLpIwd97AglCukIk=";
}
