# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon";
    rev = "9fcf5d41922f40a56f7da2174d0446580d249490";
    sha256 = "0n95s7bi2pdzrn2fn0165ryrqa04j6ll46mghr2k8dg4fgbqh6w3";
  };
in applyPatches {
  inherit src;
  patches = [];
}
